// Fixes the generic "<Name> gym package" descriptions that get auto-created
// the first time someone registers for a plan that doesn't exist yet
// (see registrationController.js's fallback). Only touches description +
// features - leaves price, discountPrice, and badge exactly as they are,
// so it won't undo any pricing changes you've made from the admin panel.
//
// Safe to re-run.
//
// Run from the backend/ folder:
//   node scripts/fixPlanDescriptions.js

import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Plan from '../models/Plan.js';
import dns from 'dns';

dns.setServers(['8.8.8.8', '8.8.4.4']);

dotenv.config();

const fixes = {
    weekly: {
        description: 'Try it out, no commitment.',
        features: ['Full gym access', 'Locker room', 'Free fitness assessment'],
    },
    monthly: {
        description: 'Most people start here.',
        features: [
            'Full gym access',
            'Locker room',
            'Free fitness assessment',
            '1 personal training session',
            'Group classes',
        ],
    },
    yearly: {
        description: 'Best value, biggest commitment.',
        features: [
            'Full gym access',
            'Locker room',
            'Free fitness assessment',
            '4 personal training sessions',
            'Group classes',
            'Nutrition consultation',
        ],
    },
};

async function run() {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    const plans = await Plan.find({});
    let updated = 0;

    for (const plan of plans) {
        const key = plan.name.trim().toLowerCase();
        const fix = fixes[key];
        if (!fix) continue;

        // Only touch it if it still looks like the auto-generated placeholder,
        // so this never clobbers a description you've since written yourself.
        const looksAutoGenerated =
            !plan.description || /^\s*\S+\s+gym package\s*$/i.test(plan.description);

        if (!looksAutoGenerated) {
            console.log(`↷ Skipped "${plan.name}" - description already customized`);
            continue;
        }

        plan.description = fix.description;
        if (!plan.features || plan.features.length === 0) {
            plan.features = fix.features;
        }
        await plan.save();
        console.log(`✅ Fixed "${plan.name}" description`);
        updated += 1;
    }

    console.log(updated === 0 ? 'Nothing to fix.' : `Updated ${updated} plan(s).`);

    await mongoose.disconnect();
}

run().catch((err) => {
    console.error('Fix failed:', err);
    process.exit(1);
});